# Generated by Django 5.2.11 on 2026-02-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionevent',
            name='threshold',
            field=models.FloatField(default=0.25),
        ),
    ]
