# Generated by Django 5.2.11 on 2026-03-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0002_alter_motionevent_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motionevent',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
