# Generated by Django 6.0.3 on 2026-05-09 14:53

import uuid
from django.db import migrations, models


def populate_motion_event_uuids(apps, schema_editor):
    MotionEvent = apps.get_model('motions', 'MotionEvent')
    for motion_event in MotionEvent.objects.filter(uuid__isnull=True):
        motion_event.uuid = uuid.uuid4()
        motion_event.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('motions', '0003_alter_motionevent_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='motionevent',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_motion_event_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='motionevent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
