# Generated by Django 5.2.11 on 2026-02-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='motion_sensitivity',
        ),
    ]
