# Generated by Django 6.0.3 on 2026-05-09 14:53

import uuid
from django.db import migrations, models


def populate_camera_uuids(apps, schema_editor):
    Camera = apps.get_model('cameras', 'Camera')
    for camera in Camera.objects.filter(uuid__isnull=True):
        camera.uuid = uuid.uuid4()
        camera.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_remove_camera_motion_sensitivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_camera_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='camera',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
