# Generated by Django 6.0.3 on 2026-05-09 14:53

import uuid
from django.db import migrations, models


def populate_image_uuids(apps, schema_editor):
    Image = apps.get_model('images', 'Image')
    for image in Image.objects.filter(uuid__isnull=True):
        image.uuid = uuid.uuid4()
        image.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_image_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
